name: ci-node-with-express-workflow
on:
  pull_request:
    branches:
      - develop
      
jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18.3.0', '16.15.1']    
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm i
      - name: Run tests
        run: npm test
